name       : xorgproto
version    : '2019.2'
release    : 3
source     :
    - https://xorg.freedesktop.org/archive/individual/proto/xorgproto-2019.2.tar.bz2 : 46ecd0156c561d41e8aa87ce79340910cdf38373b759e737fcbba5df508e7b8e
license    : MIT
summary    : X Window System Core Protocol
component  : xorg.proto
description: |
    This package provides the headers and specification documents defining the core protocol and (many) extensions for the X Window System. The extensions are those common among servers descended from X.Org 6.7. It also includes a number of headers that aren't purely protocol related, but are depended upon by many other X Window System packages to provide common definitions and porting layer.
patterns   : /
setup      : |
    %meson_configure -Dlegacy=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Cleanup unwanted headers so they aren't used by accident in builds
    rm $installdir/usr/share/pkgconfig/{apple,windows}wmproto.pc
    rm $installdir/usr/include/X11/extensions/{apple,windows}wm*
    rm $installdir/usr/include/X11/extensions/XKBgeom.h
