name       : xorgproto
version    : '2018.4'
release    : 2
source     :
    - https://xorg.freedesktop.org/archive/individual/proto/xorgproto-2018.4.tar.bz2 : fee885e0512899ea5280c593fdb2735beb1693ad170c22ebcc844470eec415a0
license    : MIT
summary    : X Window System Core Protocol
component  : xorg.proto
description: |
    This package provides the headers and specification documents defining the core protocol and (many) extensions for the X Window System. The extensions are those common among servers descended from X.Org 6.7. It also includes a number of headers that aren't purely protocol related, but are depended upon by many other X Window System packages to provide common definitions and porting layer.
patterns   : /
setup      : |
    %meson_configure -Dlegacy=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Cleanup unwanted headers so they aren't used by accident in builds
    rm $installdir/usr/share/pkgconfig/{apple,windows}wmproto.pc
    rm $installdir/usr/include/X11/extensions/{apple,windows}wm*
